(cl:defpackage drone_controller-srv
  (:use )
  (:export
   "GOHOME"
   "<GOHOME-REQUEST>"
   "GOHOME-REQUEST"
   "<GOHOME-RESPONSE>"
   "GOHOME-RESPONSE"
   "GOTOPOINT"
   "<GOTOPOINT-REQUEST>"
   "GOTOPOINT-REQUEST"
   "<GOTOPOINT-RESPONSE>"
   "GOTOPOINT-RESPONSE"
   "LAND"
   "<LAND-REQUEST>"
   "LAND-REQUEST"
   "<LAND-RESPONSE>"
   "LAND-RESPONSE"
   "TAKEOFF"
   "<TAKEOFF-REQUEST>"
   "TAKEOFF-REQUEST"
   "<TAKEOFF-RESPONSE>"
   "TAKEOFF-RESPONSE"
  ))

