// Generated by gencpp from file drone_controller/GoHomeRequest.msg
// DO NOT EDIT!


#ifndef DRONE_CONTROLLER_MESSAGE_GOHOMEREQUEST_H
#define DRONE_CONTROLLER_MESSAGE_GOHOMEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drone_controller
{
template <class ContainerAllocator>
struct GoHomeRequest_
{
  typedef GoHomeRequest_<ContainerAllocator> Type;

  GoHomeRequest_()
    : data(0)  {
    }
  GoHomeRequest_(const ContainerAllocator& _alloc)
    : data(0)  {
  (void)_alloc;
    }



   typedef int8_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::drone_controller::GoHomeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drone_controller::GoHomeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GoHomeRequest_

typedef ::drone_controller::GoHomeRequest_<std::allocator<void> > GoHomeRequest;

typedef boost::shared_ptr< ::drone_controller::GoHomeRequest > GoHomeRequestPtr;
typedef boost::shared_ptr< ::drone_controller::GoHomeRequest const> GoHomeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drone_controller::GoHomeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drone_controller::GoHomeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::drone_controller::GoHomeRequest_<ContainerAllocator1> & lhs, const ::drone_controller::GoHomeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::drone_controller::GoHomeRequest_<ContainerAllocator1> & lhs, const ::drone_controller::GoHomeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace drone_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::drone_controller::GoHomeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_controller::GoHomeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_controller::GoHomeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_controller::GoHomeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_controller::GoHomeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_controller::GoHomeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drone_controller::GoHomeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "27ffa0c9c4b8fb8492252bcad9e5c57b";
  }

  static const char* value(const ::drone_controller::GoHomeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x27ffa0c9c4b8fb84ULL;
  static const uint64_t static_value2 = 0x92252bcad9e5c57bULL;
};

template<class ContainerAllocator>
struct DataType< ::drone_controller::GoHomeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drone_controller/GoHomeRequest";
  }

  static const char* value(const ::drone_controller::GoHomeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drone_controller::GoHomeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 data    		# integer with a flag\n"
;
  }

  static const char* value(const ::drone_controller::GoHomeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drone_controller::GoHomeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoHomeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drone_controller::GoHomeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drone_controller::GoHomeRequest_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<int8_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONE_CONTROLLER_MESSAGE_GOHOMEREQUEST_H
