// Generated by gencpp from file drone_controller/GoHome.msg
// DO NOT EDIT!


#ifndef DRONE_CONTROLLER_MESSAGE_GOHOME_H
#define DRONE_CONTROLLER_MESSAGE_GOHOME_H

#include <ros/service_traits.h>


#include <drone_controller/GoHomeRequest.h>
#include <drone_controller/GoHomeResponse.h>


namespace drone_controller
{

struct GoHome
{

typedef GoHomeRequest Request;
typedef GoHomeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoHome
} // namespace drone_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::drone_controller::GoHome > {
  static const char* value()
  {
    return "cbb2fae3170f584c2b25f43322fecf10";
  }

  static const char* value(const ::drone_controller::GoHome&) { return value(); }
};

template<>
struct DataType< ::drone_controller::GoHome > {
  static const char* value()
  {
    return "drone_controller/GoHome";
  }

  static const char* value(const ::drone_controller::GoHome&) { return value(); }
};


// service_traits::MD5Sum< ::drone_controller::GoHomeRequest> should match
// service_traits::MD5Sum< ::drone_controller::GoHome >
template<>
struct MD5Sum< ::drone_controller::GoHomeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::drone_controller::GoHome >::value();
  }
  static const char* value(const ::drone_controller::GoHomeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::drone_controller::GoHomeRequest> should match
// service_traits::DataType< ::drone_controller::GoHome >
template<>
struct DataType< ::drone_controller::GoHomeRequest>
{
  static const char* value()
  {
    return DataType< ::drone_controller::GoHome >::value();
  }
  static const char* value(const ::drone_controller::GoHomeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::drone_controller::GoHomeResponse> should match
// service_traits::MD5Sum< ::drone_controller::GoHome >
template<>
struct MD5Sum< ::drone_controller::GoHomeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::drone_controller::GoHome >::value();
  }
  static const char* value(const ::drone_controller::GoHomeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::drone_controller::GoHomeResponse> should match
// service_traits::DataType< ::drone_controller::GoHome >
template<>
struct DataType< ::drone_controller::GoHomeResponse>
{
  static const char* value()
  {
    return DataType< ::drone_controller::GoHome >::value();
  }
  static const char* value(const ::drone_controller::GoHomeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DRONE_CONTROLLER_MESSAGE_GOHOME_H
