// Generated by gencpp from file drone_controller/GoToPointResponse.msg
// DO NOT EDIT!


#ifndef DRONE_CONTROLLER_MESSAGE_GOTOPOINTRESPONSE_H
#define DRONE_CONTROLLER_MESSAGE_GOTOPOINTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drone_controller
{
template <class ContainerAllocator>
struct GoToPointResponse_
{
  typedef GoToPointResponse_<ContainerAllocator> Type;

  GoToPointResponse_()
    : ack(false)  {
    }
  GoToPointResponse_(const ContainerAllocator& _alloc)
    : ack(false)  {
  (void)_alloc;
    }



   typedef uint8_t _ack_type;
  _ack_type ack;





  typedef boost::shared_ptr< ::drone_controller::GoToPointResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drone_controller::GoToPointResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GoToPointResponse_

typedef ::drone_controller::GoToPointResponse_<std::allocator<void> > GoToPointResponse;

typedef boost::shared_ptr< ::drone_controller::GoToPointResponse > GoToPointResponsePtr;
typedef boost::shared_ptr< ::drone_controller::GoToPointResponse const> GoToPointResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drone_controller::GoToPointResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drone_controller::GoToPointResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::drone_controller::GoToPointResponse_<ContainerAllocator1> & lhs, const ::drone_controller::GoToPointResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ack == rhs.ack;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::drone_controller::GoToPointResponse_<ContainerAllocator1> & lhs, const ::drone_controller::GoToPointResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace drone_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::drone_controller::GoToPointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_controller::GoToPointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_controller::GoToPointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_controller::GoToPointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_controller::GoToPointResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_controller::GoToPointResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drone_controller::GoToPointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f5729177853f34b146e2e57766d4dc2";
  }

  static const char* value(const ::drone_controller::GoToPointResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f5729177853f34bULL;
  static const uint64_t static_value2 = 0x146e2e57766d4dc2ULL;
};

template<class ContainerAllocator>
struct DataType< ::drone_controller::GoToPointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drone_controller/GoToPointResponse";
  }

  static const char* value(const ::drone_controller::GoToPointResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drone_controller::GoToPointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool ack 			# acknowledged information\n"
;
  }

  static const char* value(const ::drone_controller::GoToPointResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drone_controller::GoToPointResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ack);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToPointResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drone_controller::GoToPointResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drone_controller::GoToPointResponse_<ContainerAllocator>& v)
  {
    s << indent << "ack: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ack);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONE_CONTROLLER_MESSAGE_GOTOPOINTRESPONSE_H
