//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the drone_controller package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __drone_controller__PARAMSCONFIG_H__
#define __drone_controller__PARAMSCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace drone_controller
{
  class ParamsConfigStatics;

  class ParamsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(ParamsConfig &config, const ParamsConfig &max, const ParamsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const ParamsConfig &config1, const ParamsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, ParamsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const ParamsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ParamsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const ParamsConfig &config) const = 0;
      virtual void getValue(const ParamsConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T ParamsConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T ParamsConfig::* field;

      virtual void clamp(ParamsConfig &config, const ParamsConfig &max, const ParamsConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const ParamsConfig &config1, const ParamsConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, ParamsConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const ParamsConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ParamsConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const ParamsConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const ParamsConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, ParamsConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, ParamsConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<ParamsConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(ParamsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);


      }
    }

    

    bool state;
    std::string name;

    class ROOM_CONFIGURATION
{
  public:
    ROOM_CONFIGURATION()
    {
      state = true;
      name = "Room_Configuration";
    }

    void setParams(ParamsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("room_max_x"==(*_i)->name){room_max_x = boost::any_cast<double>(val);}
        if("room_min_x"==(*_i)->name){room_min_x = boost::any_cast<double>(val);}
        if("room_max_y"==(*_i)->name){room_max_y = boost::any_cast<double>(val);}
        if("room_min_y"==(*_i)->name){room_min_y = boost::any_cast<double>(val);}
        if("room_max_z"==(*_i)->name){room_max_z = boost::any_cast<double>(val);}
        if("room_min_z"==(*_i)->name){room_min_z = boost::any_cast<double>(val);}
      }
    }

    double room_max_x;
double room_min_x;
double room_max_y;
double room_min_y;
double room_max_z;
double room_min_z;

    bool state;
    std::string name;

    
}room_configuration;

class PID_PITCH_CONFIGURATION
{
  public:
    PID_PITCH_CONFIGURATION()
    {
      state = true;
      name = "PID_Pitch_Configuration";
    }

    void setParams(ParamsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("Kp_x"==(*_i)->name){Kp_x = boost::any_cast<double>(val);}
        if("Ki_x"==(*_i)->name){Ki_x = boost::any_cast<double>(val);}
        if("Kd_x"==(*_i)->name){Kd_x = boost::any_cast<double>(val);}
        if("init_d_x"==(*_i)->name){init_d_x = boost::any_cast<double>(val);}
        if("output_limit_min_x"==(*_i)->name){output_limit_min_x = boost::any_cast<double>(val);}
        if("output_limit_max_x"==(*_i)->name){output_limit_max_x = boost::any_cast<double>(val);}
        if("windup_limit_min_x"==(*_i)->name){windup_limit_min_x = boost::any_cast<double>(val);}
        if("windup_limit_max_x"==(*_i)->name){windup_limit_max_x = boost::any_cast<double>(val);}
      }
    }

    double Kp_x;
double Ki_x;
double Kd_x;
double init_d_x;
double output_limit_min_x;
double output_limit_max_x;
double windup_limit_min_x;
double windup_limit_max_x;

    bool state;
    std::string name;

    
}pid_pitch_configuration;

class PID_ROLL_CONFIGURATION
{
  public:
    PID_ROLL_CONFIGURATION()
    {
      state = true;
      name = "PID_Roll_Configuration";
    }

    void setParams(ParamsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("Kp_y"==(*_i)->name){Kp_y = boost::any_cast<double>(val);}
        if("Ki_y"==(*_i)->name){Ki_y = boost::any_cast<double>(val);}
        if("Kd_y"==(*_i)->name){Kd_y = boost::any_cast<double>(val);}
        if("init_d_y"==(*_i)->name){init_d_y = boost::any_cast<double>(val);}
        if("output_limit_min_y"==(*_i)->name){output_limit_min_y = boost::any_cast<double>(val);}
        if("output_limit_max_y"==(*_i)->name){output_limit_max_y = boost::any_cast<double>(val);}
        if("windup_limit_min_y"==(*_i)->name){windup_limit_min_y = boost::any_cast<double>(val);}
        if("windup_limit_max_y"==(*_i)->name){windup_limit_max_y = boost::any_cast<double>(val);}
      }
    }

    double Kp_y;
double Ki_y;
double Kd_y;
double init_d_y;
double output_limit_min_y;
double output_limit_max_y;
double windup_limit_min_y;
double windup_limit_max_y;

    bool state;
    std::string name;

    
}pid_roll_configuration;

class PID_ALTITUDE_CONFIGURATION
{
  public:
    PID_ALTITUDE_CONFIGURATION()
    {
      state = true;
      name = "PID_Altitude_Configuration";
    }

    void setParams(ParamsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("Kp_z"==(*_i)->name){Kp_z = boost::any_cast<double>(val);}
        if("Ki_z"==(*_i)->name){Ki_z = boost::any_cast<double>(val);}
        if("Kd_z"==(*_i)->name){Kd_z = boost::any_cast<double>(val);}
        if("init_d_z"==(*_i)->name){init_d_z = boost::any_cast<double>(val);}
        if("output_limit_min_z"==(*_i)->name){output_limit_min_z = boost::any_cast<double>(val);}
        if("output_limit_max_z"==(*_i)->name){output_limit_max_z = boost::any_cast<double>(val);}
        if("windup_limit_min_z"==(*_i)->name){windup_limit_min_z = boost::any_cast<double>(val);}
        if("windup_limit_max_z"==(*_i)->name){windup_limit_max_z = boost::any_cast<double>(val);}
      }
    }

    double Kp_z;
double Ki_z;
double Kd_z;
double init_d_z;
double output_limit_min_z;
double output_limit_max_z;
double windup_limit_min_z;
double windup_limit_max_z;

    bool state;
    std::string name;

    
}pid_altitude_configuration;

class CONTROL_CONFIGURATION
{
  public:
    CONTROL_CONFIGURATION()
    {
      state = true;
      name = "Control_Configuration";
    }

    void setParams(ParamsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("fs"==(*_i)->name){fs = boost::any_cast<int>(val);}
        if("Tc"==(*_i)->name){Tc = boost::any_cast<double>(val);}
        if("angle_mode"==(*_i)->name){angle_mode = boost::any_cast<bool>(val);}
        if("exp_acrobatic_model"==(*_i)->name){exp_acrobatic_model = boost::any_cast<bool>(val);}
        if("trust_as_trust"==(*_i)->name){trust_as_trust = boost::any_cast<bool>(val);}
        if("static_trust"==(*_i)->name){static_trust = boost::any_cast<double>(val);}
        if("world_frame"==(*_i)->name){world_frame = boost::any_cast<std::string>(val);}
        if("drone_frame"==(*_i)->name){drone_frame = boost::any_cast<std::string>(val);}
      }
    }

    int fs;
double Tc;
bool angle_mode;
bool exp_acrobatic_model;
bool trust_as_trust;
double static_trust;
std::string world_frame;
std::string drone_frame;

    bool state;
    std::string name;

    
}control_configuration;

}groups;



//#line 53 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double room_max_x;
//#line 54 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double room_min_x;
//#line 55 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double room_max_y;
//#line 56 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double room_min_y;
//#line 57 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double room_max_z;
//#line 58 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double room_min_z;
//#line 25 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double Kp_x;
//#line 26 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double Ki_x;
//#line 27 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double Kd_x;
//#line 28 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double init_d_x;
//#line 29 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double output_limit_min_x;
//#line 30 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double output_limit_max_x;
//#line 31 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double windup_limit_min_x;
//#line 32 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double windup_limit_max_x;
//#line 35 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double Kp_y;
//#line 36 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double Ki_y;
//#line 37 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double Kd_y;
//#line 38 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double init_d_y;
//#line 39 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double output_limit_min_y;
//#line 40 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double output_limit_max_y;
//#line 41 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double windup_limit_min_y;
//#line 42 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double windup_limit_max_y;
//#line 44 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double Kp_z;
//#line 45 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double Ki_z;
//#line 46 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double Kd_z;
//#line 47 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double init_d_z;
//#line 48 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double output_limit_min_z;
//#line 49 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double output_limit_max_z;
//#line 50 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double windup_limit_min_z;
//#line 51 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double windup_limit_max_z;
//#line 15 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      int fs;
//#line 16 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double Tc;
//#line 17 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      bool angle_mode;
//#line 18 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      bool exp_acrobatic_model;
//#line 19 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      bool trust_as_trust;
//#line 20 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      double static_trust;
//#line 21 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      std::string world_frame;
//#line 22 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      std::string drone_frame;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("ParamsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const ParamsConfig &__max__ = __getMax__();
      const ParamsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const ParamsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const ParamsConfig &__getDefault__();
    static const ParamsConfig &__getMax__();
    static const ParamsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const ParamsConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void ParamsConfig::ParamDescription<std::string>::clamp(ParamsConfig &config, const ParamsConfig &max, const ParamsConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class ParamsConfigStatics
  {
    friend class ParamsConfig;

    ParamsConfigStatics()
    {
ParamsConfig::GroupDescription<ParamsConfig::DEFAULT, ParamsConfig> Default("Default", "", 0, 0, true, &ParamsConfig::groups);
ParamsConfig::GroupDescription<ParamsConfig::DEFAULT::ROOM_CONFIGURATION, ParamsConfig::DEFAULT> Room_Configuration("Room_Configuration", "", 0, 1, true, &ParamsConfig::DEFAULT::room_configuration);
//#line 53 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.room_max_x = -15.0;
//#line 53 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.room_max_x = 15.0;
//#line 53 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.room_max_x = 0.0;
//#line 53 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      Room_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("room_max_x", "double", 0, "Distance to the nearest obstacle in the positive X-Axis (world frame)", "", &ParamsConfig::room_max_x)));
//#line 53 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("room_max_x", "double", 0, "Distance to the nearest obstacle in the positive X-Axis (world frame)", "", &ParamsConfig::room_max_x)));
//#line 54 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.room_min_x = -15.0;
//#line 54 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.room_min_x = 15.0;
//#line 54 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.room_min_x = 0.0;
//#line 54 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      Room_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("room_min_x", "double", 0, "Distance to the nearest obstacle in the negative X-Axis (world frame)", "", &ParamsConfig::room_min_x)));
//#line 54 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("room_min_x", "double", 0, "Distance to the nearest obstacle in the negative X-Axis (world frame)", "", &ParamsConfig::room_min_x)));
//#line 55 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.room_max_y = -15.0;
//#line 55 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.room_max_y = 15.0;
//#line 55 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.room_max_y = 0.0;
//#line 55 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      Room_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("room_max_y", "double", 0, "Distance to the nearest obstacle in the positive Y-Axis (world frame)", "", &ParamsConfig::room_max_y)));
//#line 55 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("room_max_y", "double", 0, "Distance to the nearest obstacle in the positive Y-Axis (world frame)", "", &ParamsConfig::room_max_y)));
//#line 56 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.room_min_y = -15.0;
//#line 56 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.room_min_y = 15.0;
//#line 56 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.room_min_y = 0.0;
//#line 56 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      Room_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("room_min_y", "double", 0, "Distance to the nearest obstacle in the negative Y-Axis (world frame)", "", &ParamsConfig::room_min_y)));
//#line 56 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("room_min_y", "double", 0, "Distance to the nearest obstacle in the negative Y-Axis (world frame)", "", &ParamsConfig::room_min_y)));
//#line 57 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.room_max_z = -15.0;
//#line 57 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.room_max_z = 15.0;
//#line 57 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.room_max_z = 0.0;
//#line 57 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      Room_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("room_max_z", "double", 0, "Distance to the nearest obstacle in the positive Z-Axis (world frame)", "", &ParamsConfig::room_max_z)));
//#line 57 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("room_max_z", "double", 0, "Distance to the nearest obstacle in the positive Z-Axis (world frame)", "", &ParamsConfig::room_max_z)));
//#line 58 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.room_min_z = -15.0;
//#line 58 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.room_min_z = 15.0;
//#line 58 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.room_min_z = 0.0;
//#line 58 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      Room_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("room_min_z", "double", 0, "Distance to the nearest obstacle in the negative Z-Axis (world frame)", "", &ParamsConfig::room_min_z)));
//#line 58 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("room_min_z", "double", 0, "Distance to the nearest obstacle in the negative Z-Axis (world frame)", "", &ParamsConfig::room_min_z)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Room_Configuration.convertParams();
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(ParamsConfig::AbstractGroupDescriptionConstPtr(new ParamsConfig::GroupDescription<ParamsConfig::DEFAULT::ROOM_CONFIGURATION, ParamsConfig::DEFAULT>(Room_Configuration)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ParamsConfig::AbstractGroupDescriptionConstPtr(new ParamsConfig::GroupDescription<ParamsConfig::DEFAULT::ROOM_CONFIGURATION, ParamsConfig::DEFAULT>(Room_Configuration)));
ParamsConfig::GroupDescription<ParamsConfig::DEFAULT::PID_PITCH_CONFIGURATION, ParamsConfig::DEFAULT> PID_Pitch_Configuration("PID_Pitch_Configuration", "", 0, 2, true, &ParamsConfig::DEFAULT::pid_pitch_configuration);
//#line 25 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.Kp_x = 0.0;
//#line 25 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.Kp_x = 10.0;
//#line 25 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.Kp_x = 4.0;
//#line 25 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      PID_Pitch_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("Kp_x", "double", 0, "PID Kp", "", &ParamsConfig::Kp_x)));
//#line 25 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("Kp_x", "double", 0, "PID Kp", "", &ParamsConfig::Kp_x)));
//#line 26 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.Ki_x = 0.0;
//#line 26 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.Ki_x = 3.0;
//#line 26 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.Ki_x = 1.0;
//#line 26 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      PID_Pitch_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("Ki_x", "double", 0, "PID Ki", "", &ParamsConfig::Ki_x)));
//#line 26 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("Ki_x", "double", 0, "PID Ki", "", &ParamsConfig::Ki_x)));
//#line 27 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.Kd_x = 0.0;
//#line 27 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.Kd_x = 10.0;
//#line 27 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.Kd_x = 2.0;
//#line 27 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      PID_Pitch_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("Kd_x", "double", 0, "PID Kd", "", &ParamsConfig::Kd_x)));
//#line 27 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("Kd_x", "double", 0, "PID Kd", "", &ParamsConfig::Kd_x)));
//#line 28 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.init_d_x = 0.0;
//#line 28 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.init_d_x = 10.0;
//#line 28 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.init_d_x = 0.0;
//#line 28 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      PID_Pitch_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("init_d_x", "double", 0, "Initialization Value for the integral contribution", "", &ParamsConfig::init_d_x)));
//#line 28 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("init_d_x", "double", 0, "Initialization Value for the integral contribution", "", &ParamsConfig::init_d_x)));
//#line 29 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.output_limit_min_x = -8.0;
//#line 29 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.output_limit_min_x = 0.0;
//#line 29 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.output_limit_min_x = -4.0;
//#line 29 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      PID_Pitch_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("output_limit_min_x", "double", 0, "Lower-bound of the PID output", "", &ParamsConfig::output_limit_min_x)));
//#line 29 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("output_limit_min_x", "double", 0, "Lower-bound of the PID output", "", &ParamsConfig::output_limit_min_x)));
//#line 30 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.output_limit_max_x = 0.0;
//#line 30 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.output_limit_max_x = 8.0;
//#line 30 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.output_limit_max_x = 4.0;
//#line 30 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      PID_Pitch_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("output_limit_max_x", "double", 0, "Upper-bound of the PID output", "", &ParamsConfig::output_limit_max_x)));
//#line 30 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("output_limit_max_x", "double", 0, "Upper-bound of the PID output", "", &ParamsConfig::output_limit_max_x)));
//#line 31 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.windup_limit_min_x = -8.0;
//#line 31 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.windup_limit_min_x = 0.0;
//#line 31 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.windup_limit_min_x = -4.0;
//#line 31 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      PID_Pitch_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("windup_limit_min_x", "double", 0, "Lower-bound of the PID windup", "", &ParamsConfig::windup_limit_min_x)));
//#line 31 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("windup_limit_min_x", "double", 0, "Lower-bound of the PID windup", "", &ParamsConfig::windup_limit_min_x)));
//#line 32 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.windup_limit_max_x = 0.0;
//#line 32 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.windup_limit_max_x = 8.0;
//#line 32 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.windup_limit_max_x = 4.0;
//#line 32 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      PID_Pitch_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("windup_limit_max_x", "double", 0, "Upper-bound of the PID windup", "", &ParamsConfig::windup_limit_max_x)));
//#line 32 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("windup_limit_max_x", "double", 0, "Upper-bound of the PID windup", "", &ParamsConfig::windup_limit_max_x)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      PID_Pitch_Configuration.convertParams();
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(ParamsConfig::AbstractGroupDescriptionConstPtr(new ParamsConfig::GroupDescription<ParamsConfig::DEFAULT::PID_PITCH_CONFIGURATION, ParamsConfig::DEFAULT>(PID_Pitch_Configuration)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ParamsConfig::AbstractGroupDescriptionConstPtr(new ParamsConfig::GroupDescription<ParamsConfig::DEFAULT::PID_PITCH_CONFIGURATION, ParamsConfig::DEFAULT>(PID_Pitch_Configuration)));
ParamsConfig::GroupDescription<ParamsConfig::DEFAULT::PID_ROLL_CONFIGURATION, ParamsConfig::DEFAULT> PID_Roll_Configuration("PID_Roll_Configuration", "", 0, 3, true, &ParamsConfig::DEFAULT::pid_roll_configuration);
//#line 35 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.Kp_y = 0.0;
//#line 35 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.Kp_y = 10.0;
//#line 35 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.Kp_y = 4.0;
//#line 35 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      PID_Roll_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("Kp_y", "double", 0, "PID Kp", "", &ParamsConfig::Kp_y)));
//#line 35 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("Kp_y", "double", 0, "PID Kp", "", &ParamsConfig::Kp_y)));
//#line 36 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.Ki_y = 0.0;
//#line 36 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.Ki_y = 3.0;
//#line 36 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.Ki_y = 1.0;
//#line 36 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      PID_Roll_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("Ki_y", "double", 0, "PID Ki", "", &ParamsConfig::Ki_y)));
//#line 36 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("Ki_y", "double", 0, "PID Ki", "", &ParamsConfig::Ki_y)));
//#line 37 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.Kd_y = 0.0;
//#line 37 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.Kd_y = 10.0;
//#line 37 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.Kd_y = 2.0;
//#line 37 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      PID_Roll_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("Kd_y", "double", 0, "PID Kd", "", &ParamsConfig::Kd_y)));
//#line 37 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("Kd_y", "double", 0, "PID Kd", "", &ParamsConfig::Kd_y)));
//#line 38 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.init_d_y = 0.0;
//#line 38 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.init_d_y = 10.0;
//#line 38 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.init_d_y = 0.0;
//#line 38 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      PID_Roll_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("init_d_y", "double", 0, "Initialization Value for the integral contribution", "", &ParamsConfig::init_d_y)));
//#line 38 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("init_d_y", "double", 0, "Initialization Value for the integral contribution", "", &ParamsConfig::init_d_y)));
//#line 39 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.output_limit_min_y = -8.0;
//#line 39 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.output_limit_min_y = 0.0;
//#line 39 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.output_limit_min_y = -4.0;
//#line 39 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      PID_Roll_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("output_limit_min_y", "double", 0, "Lower-bound of the PID output", "", &ParamsConfig::output_limit_min_y)));
//#line 39 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("output_limit_min_y", "double", 0, "Lower-bound of the PID output", "", &ParamsConfig::output_limit_min_y)));
//#line 40 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.output_limit_max_y = 0.0;
//#line 40 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.output_limit_max_y = 8.0;
//#line 40 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.output_limit_max_y = 4.0;
//#line 40 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      PID_Roll_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("output_limit_max_y", "double", 0, "Upper-bound of the PID output", "", &ParamsConfig::output_limit_max_y)));
//#line 40 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("output_limit_max_y", "double", 0, "Upper-bound of the PID output", "", &ParamsConfig::output_limit_max_y)));
//#line 41 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.windup_limit_min_y = -8.0;
//#line 41 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.windup_limit_min_y = 0.0;
//#line 41 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.windup_limit_min_y = -4.0;
//#line 41 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      PID_Roll_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("windup_limit_min_y", "double", 0, "Lower-bound of the PID windup", "", &ParamsConfig::windup_limit_min_y)));
//#line 41 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("windup_limit_min_y", "double", 0, "Lower-bound of the PID windup", "", &ParamsConfig::windup_limit_min_y)));
//#line 42 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.windup_limit_max_y = 0.0;
//#line 42 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.windup_limit_max_y = 8.0;
//#line 42 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.windup_limit_max_y = 4.0;
//#line 42 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      PID_Roll_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("windup_limit_max_y", "double", 0, "Upper-bound of the PID windup", "", &ParamsConfig::windup_limit_max_y)));
//#line 42 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("windup_limit_max_y", "double", 0, "Upper-bound of the PID windup", "", &ParamsConfig::windup_limit_max_y)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      PID_Roll_Configuration.convertParams();
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(ParamsConfig::AbstractGroupDescriptionConstPtr(new ParamsConfig::GroupDescription<ParamsConfig::DEFAULT::PID_ROLL_CONFIGURATION, ParamsConfig::DEFAULT>(PID_Roll_Configuration)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ParamsConfig::AbstractGroupDescriptionConstPtr(new ParamsConfig::GroupDescription<ParamsConfig::DEFAULT::PID_ROLL_CONFIGURATION, ParamsConfig::DEFAULT>(PID_Roll_Configuration)));
ParamsConfig::GroupDescription<ParamsConfig::DEFAULT::PID_ALTITUDE_CONFIGURATION, ParamsConfig::DEFAULT> PID_Altitude_Configuration("PID_Altitude_Configuration", "", 0, 4, true, &ParamsConfig::DEFAULT::pid_altitude_configuration);
//#line 44 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.Kp_z = 0.0;
//#line 44 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.Kp_z = 10.0;
//#line 44 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.Kp_z = 4.5;
//#line 44 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      PID_Altitude_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("Kp_z", "double", 0, "PID Kp", "", &ParamsConfig::Kp_z)));
//#line 44 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("Kp_z", "double", 0, "PID Kp", "", &ParamsConfig::Kp_z)));
//#line 45 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.Ki_z = 0.0;
//#line 45 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.Ki_z = 3.0;
//#line 45 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.Ki_z = 1.2;
//#line 45 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      PID_Altitude_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("Ki_z", "double", 0, "PID Ki", "", &ParamsConfig::Ki_z)));
//#line 45 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("Ki_z", "double", 0, "PID Ki", "", &ParamsConfig::Ki_z)));
//#line 46 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.Kd_z = 0.0;
//#line 46 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.Kd_z = 10.0;
//#line 46 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.Kd_z = 3.0;
//#line 46 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      PID_Altitude_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("Kd_z", "double", 0, "PID Kd", "", &ParamsConfig::Kd_z)));
//#line 46 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("Kd_z", "double", 0, "PID Kd", "", &ParamsConfig::Kd_z)));
//#line 47 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.init_d_z = 0.0;
//#line 47 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.init_d_z = 10.0;
//#line 47 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.init_d_z = 0.0;
//#line 47 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      PID_Altitude_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("init_d_z", "double", 0, "Initialization Value for the integral contribution", "", &ParamsConfig::init_d_z)));
//#line 47 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("init_d_z", "double", 0, "Initialization Value for the integral contribution", "", &ParamsConfig::init_d_z)));
//#line 48 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.output_limit_min_z = -20.0;
//#line 48 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.output_limit_min_z = 0.0;
//#line 48 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.output_limit_min_z = -9.8;
//#line 48 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      PID_Altitude_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("output_limit_min_z", "double", 0, "Lower-bound of the PID output", "", &ParamsConfig::output_limit_min_z)));
//#line 48 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("output_limit_min_z", "double", 0, "Lower-bound of the PID output", "", &ParamsConfig::output_limit_min_z)));
//#line 49 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.output_limit_max_z = 0.0;
//#line 49 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.output_limit_max_z = 20.0;
//#line 49 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.output_limit_max_z = 9.8;
//#line 49 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      PID_Altitude_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("output_limit_max_z", "double", 0, "Upper-bound of the PID output", "", &ParamsConfig::output_limit_max_z)));
//#line 49 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("output_limit_max_z", "double", 0, "Upper-bound of the PID output", "", &ParamsConfig::output_limit_max_z)));
//#line 50 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.windup_limit_min_z = -20.0;
//#line 50 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.windup_limit_min_z = 0.0;
//#line 50 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.windup_limit_min_z = -9.8;
//#line 50 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      PID_Altitude_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("windup_limit_min_z", "double", 0, "Lower-bound of the PID windup", "", &ParamsConfig::windup_limit_min_z)));
//#line 50 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("windup_limit_min_z", "double", 0, "Lower-bound of the PID windup", "", &ParamsConfig::windup_limit_min_z)));
//#line 51 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.windup_limit_max_z = 0.0;
//#line 51 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.windup_limit_max_z = 20.0;
//#line 51 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.windup_limit_max_z = 9.8;
//#line 51 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      PID_Altitude_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("windup_limit_max_z", "double", 0, "Upper-bound of the PID windup", "", &ParamsConfig::windup_limit_max_z)));
//#line 51 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("windup_limit_max_z", "double", 0, "Upper-bound of the PID windup", "", &ParamsConfig::windup_limit_max_z)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      PID_Altitude_Configuration.convertParams();
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(ParamsConfig::AbstractGroupDescriptionConstPtr(new ParamsConfig::GroupDescription<ParamsConfig::DEFAULT::PID_ALTITUDE_CONFIGURATION, ParamsConfig::DEFAULT>(PID_Altitude_Configuration)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ParamsConfig::AbstractGroupDescriptionConstPtr(new ParamsConfig::GroupDescription<ParamsConfig::DEFAULT::PID_ALTITUDE_CONFIGURATION, ParamsConfig::DEFAULT>(PID_Altitude_Configuration)));
ParamsConfig::GroupDescription<ParamsConfig::DEFAULT::CONTROL_CONFIGURATION, ParamsConfig::DEFAULT> Control_Configuration("Control_Configuration", "", 0, 5, true, &ParamsConfig::DEFAULT::control_configuration);
//#line 15 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.fs = 5;
//#line 15 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.fs = 100;
//#line 15 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.fs = 15;
//#line 15 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      Control_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<int>("fs", "int", 0, "Controller frequency", "", &ParamsConfig::fs)));
//#line 15 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<int>("fs", "int", 0, "Controller frequency", "", &ParamsConfig::fs)));
//#line 16 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.Tc = 1.0;
//#line 16 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.Tc = 6.0;
//#line 16 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.Tc = 3.0;
//#line 16 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      Control_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("Tc", "double", 0, "Time constant to reach the set point", "", &ParamsConfig::Tc)));
//#line 16 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("Tc", "double", 0, "Time constant to reach the set point", "", &ParamsConfig::Tc)));
//#line 17 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.angle_mode = 0;
//#line 17 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.angle_mode = 1;
//#line 17 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.angle_mode = 1;
//#line 17 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      Control_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<bool>("angle_mode", "bool", 0, "Enable Angle-Mode (Acrobatic if disabled)", "", &ParamsConfig::angle_mode)));
//#line 17 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<bool>("angle_mode", "bool", 0, "Enable Angle-Mode (Acrobatic if disabled)", "", &ParamsConfig::angle_mode)));
//#line 18 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.exp_acrobatic_model = 0;
//#line 18 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.exp_acrobatic_model = 1;
//#line 18 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.exp_acrobatic_model = 0;
//#line 18 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      Control_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<bool>("exp_acrobatic_model", "bool", 0, "Enable Experimental Acrobatic Model", "", &ParamsConfig::exp_acrobatic_model)));
//#line 18 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<bool>("exp_acrobatic_model", "bool", 0, "Enable Experimental Acrobatic Model", "", &ParamsConfig::exp_acrobatic_model)));
//#line 19 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.trust_as_trust = 0;
//#line 19 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.trust_as_trust = 1;
//#line 19 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.trust_as_trust = 1;
//#line 19 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      Control_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<bool>("trust_as_trust", "bool", 0, "SetAttitudeTarget interprets Thrust As Thrust", "", &ParamsConfig::trust_as_trust)));
//#line 19 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<bool>("trust_as_trust", "bool", 0, "SetAttitudeTarget interprets Thrust As Thrust", "", &ParamsConfig::trust_as_trust)));
//#line 20 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.static_trust = 0.0;
//#line 20 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.static_trust = 1.0;
//#line 20 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.static_trust = 0.225;
//#line 20 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      Control_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("static_trust", "double", 0, "Trust needed to hover", "", &ParamsConfig::static_trust)));
//#line 20 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<double>("static_trust", "double", 0, "Trust needed to hover", "", &ParamsConfig::static_trust)));
//#line 21 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.world_frame = "";
//#line 21 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.world_frame = "";
//#line 21 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.world_frame = "world";
//#line 21 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      Control_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<std::string>("world_frame", "str", 0, "World Frame", "", &ParamsConfig::world_frame)));
//#line 21 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<std::string>("world_frame", "str", 0, "World Frame", "", &ParamsConfig::world_frame)));
//#line 22 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __min__.drone_frame = "";
//#line 22 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __max__.drone_frame = "";
//#line 22 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __default__.drone_frame = "drone";
//#line 22 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      Control_Configuration.abstract_parameters.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<std::string>("drone_frame", "str", 0, "Drone Frame", "", &ParamsConfig::drone_frame)));
//#line 22 "/home/giovanni/mav_ws/src/drone_controller/cfg/Params.cfg"
      __param_descriptions__.push_back(ParamsConfig::AbstractParamDescriptionConstPtr(new ParamsConfig::ParamDescription<std::string>("drone_frame", "str", 0, "Drone Frame", "", &ParamsConfig::drone_frame)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Control_Configuration.convertParams();
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(ParamsConfig::AbstractGroupDescriptionConstPtr(new ParamsConfig::GroupDescription<ParamsConfig::DEFAULT::CONTROL_CONFIGURATION, ParamsConfig::DEFAULT>(Control_Configuration)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ParamsConfig::AbstractGroupDescriptionConstPtr(new ParamsConfig::GroupDescription<ParamsConfig::DEFAULT::CONTROL_CONFIGURATION, ParamsConfig::DEFAULT>(Control_Configuration)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ParamsConfig::AbstractGroupDescriptionConstPtr(new ParamsConfig::GroupDescription<ParamsConfig::DEFAULT, ParamsConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<ParamsConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<ParamsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<ParamsConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    ParamsConfig __max__;
    ParamsConfig __min__;
    ParamsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const ParamsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static ParamsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &ParamsConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const ParamsConfig &ParamsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const ParamsConfig &ParamsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const ParamsConfig &ParamsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<ParamsConfig::AbstractParamDescriptionConstPtr> &ParamsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<ParamsConfig::AbstractGroupDescriptionConstPtr> &ParamsConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const ParamsConfigStatics *ParamsConfig::__get_statics__()
  {
    const static ParamsConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = ParamsConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __PARAMSRECONFIGURATOR_H__
